### ISSUE TITLE
Ask questions about the data in your paper

### ISSUE THREAD

**Issue by hgyye** [hermanwh/master-thesis#34]
Hello.
Is all the data you used in your dissertation confidential data? Do you have the relevant data given in your program in Git hub? I can't find the data in your program, could you please reply? Where can I find the data you used? Thanks!

**Comment by hermanwh** [comment]
Hi! The data is confidential and not available to the public, unfortunately.

**Comment by hgyye** [comment]
Hi, I see in your paper that you are giving modified data, is that correct?


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/18/2022 19:53 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

Hi! The data is confidential and not available to the public, unfortunately.

**Comment by hgyye** [comment]
Because I see that you have written a very good thesis and I just want to run your program, which is not running now without any data


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/18/2022 19:53 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

Hi! The data is confidential and not available to the public, unfortunately.

**Comment by hermanwh** [comment]
Thank you! The data presented in the thesis (figures, simulations etc.) is real. However, the data itself is not publicly available - I haven't had for multiple years.

I think it will be somewhat difficult to use the "program" directly without modifications. The methodology used, and thus the code itself, is closely tied to the thesis objectives. That being said, much of the code can probably be copied and used with only limited hassle.

**Comment by hgyye** [comment]
Yes, thank you very much


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/18/2022 20:17 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

Reopened #34.

**Comment by hgyye** [comment]
Greetings.
You are putting only part of the program on Git hub and part of the main program is not there is it?


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/18/2022 20:17 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

Closed #34 as completed.

**Comment by hermanwh** [comment]
All code is available in this Git repository. The only part of my thesis that is not available is the data that was used.

**Comment by hgyye** [comment]
Yes, thank you very much for replying to me out of your busy schedule.
| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/21/2022 19:51 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

All code is available in this Git repository. The only part of my thesis that is not available is the data that was used.

**Comment by hgyye** [comment]
Hello.
Sorry to bother you again, but I would like to ask if you have considered or changed the type of heat exchanger (size of the heat exchanger) during the whole process of writing the program?


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/21/2022 19:58 |
| To | ***@***.******@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |


Yes, thank you very much for replying to me out of your busy schedule.
| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/21/2022 19:51 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

All code is available in this Git repository. The only part of my thesis that is not available is the data that was used.

**Comment by hermanwh** [comment]
Hi again! In short, yes, both size and type were considered. However, non of those factors were found to have relevant impact on the thesis methodology. My supervisors and I determined that the heat exchanger types used at the relevant processing facilities were quite uniform. Size was determined not to have an impact with regards to the thesis methodology.

**Comment by hgyye** [comment]
Hello:
I'm really sorry to bother you again and again. This time I want to consult, is your my master's thesis is equivalent to only reach the running state of the heat exchanger detection, and no later maintenance of the heat exchanger to do further introduction, is this? Looking forward to hearing from you.
thank you
| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 1/4/2023 21:57 |
| To | ***@***.******@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |
Hello.
Sorry to bother you again, but I would like to ask if you have considered or changed the type of heat exchanger (size of the heat exchanger) during the whole process of writing the program?


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | ***@***.***> |
| Date | 12/21/2022 19:58 |
| To | ***@***.******@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |


Yes, thank you very much for replying to me out of your busy schedule.
| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 12/21/2022 19:51 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

All code is available in this Git repository. The only part of my thesis that is not available is the data that was used.

**Comment by hermanwh** [comment]
> Hello: I'm really sorry to bother you again and again. This time I want to consult, is your my master's thesis is equivalent to only reach the running state of the heat exchanger detection, and no later maintenance of the heat exchanger to do further introduction, is this? Looking forward to hearing from you. thank you

Hi! My thesis does not discuss or research maintenance methods or exactly _when_ to perform maintenance. It concludes that if a predictive maintenance scheme was to be implemented, the predicted deviation between expected and experienced outlet coolant temperature can be of great relevance. Using the deviation in outlet coolant temperature efficiently in this manner would require additional research, as well as gathering empirical evidence on additional facilities.

Some recommendations for further research are listed in chapter 9.3, including:
- Using simulated training data, with varying degrees of fouling, to verify and/or estimate how accurately the deviation in predicted coolant outlet temperature follows the level of fouling
- Using linear basis function expansion to make more robust linear models
- Further uncertainty assessment, both for the model uncertainty, data uncertainty and method uncertainty
- Defining a suitable predictive maintenance model
- Estimating the limit until maximum coolant capacity
- Deriving costs models
- Identifying and handling sensor failures and outlier data

**Comment by hgyye** [comment]
Thank you very much for replying to my information during your busy schedule. Your paper is really excellent and has great practical significance.
By the way, your senior brother 'E Jensen and T .  Nordhus, ‘Condition monitoring of heat exchangers in gas
processing’, Master’s thesis, Norwegian University of Science and Techno-
"Is this article not publicly available in 2019?"? We can't find it by any means here. If there is no confidential information, would you please provide me with his article and related procedures? I think your article is really excellent and has great reference value. Anyway, I really thank you very much.


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 3/22/2023 15:13 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

Hello: I'm really sorry to bother you again and again. This time I want to consult, is your my master's thesis is equivalent to only reach the running state of the heat exchanger detection, and no later maintenance of the heat exchanger to do further introduction, is this? Looking forward to hearing from you. thank you

Hi! My thesis does not discuss or research maintenance methods or exactly when to perform maintenance. It concludes that if a predictive maintenance scheme was to be implemented, the predicted deviation between expected and experienced outlet coolant temperature can be of great relevance. Using the deviation in outlet coolant temperature efficiently in this manner would require additional research, as well as gathering empirical evidence on additional facilities.

Some recommendations for further research are listed in chapter 9.3, including:

Using simulated training data, with varying degrees of fouling, to verify and/or estimate how accurately the deviation in predicted coolant outlet temperature follows the level of fouling
Using linear basis function expansion to make more robust linear models
Further uncertainty assessment, both for the model uncertainty, data uncertainty and method uncertainty
Defining a suitable predictive maintenance model
Estimating the limit until maximum coolant capacity
Deriving costs models
Identifying and handling sensor failures and outlier data

**Comment by hgyye** [comment]
Good morning!
Sorry to bother you again!
I would like to ask you two questions:
1. Have you used the relevant formulas mentioned in sections 3.1.5, 3.2.5, 4.2.3 and 4.2.4 in your graduation thesis?
2. Do you have the installation package of UinSim? We really can't find the corresponding installation package.
Wish you a happy life!
Looking forward to your reply!


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 3/22/2023 18:48 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

It appears their thesis is not publicly available. If it was, it would be able to open or download from NTNU Open. Their thesis abstract can be found here: https://ntnuopen.ntnu.no/ntnu-xmlui/handle/11250/2622620

**Comment by hermanwh** [comment]
Good morning!

1) The theory and corresponding formulas are primarily used to provide theoretical justification as to why machine learning algorithms _may_ be able to make accurate estimations in the relevant cases. The machine learning models themselves perform calculations and estimations much different than traditional formulas, and thus they are not really relevant in that sense.

2) I never used UniSim myself with regards to this thesis. I assume the product can still be purchased from Honeywell, the developers. I did, to some extent, use Neqsim, which can be found here: https://equinor.github.io/neqsimhome/

**Comment by hgyye** [comment]
Thank you very much for taking time out of your busy schedule to help me answer, I wish you a happy life.


| |
侯刚
|
|
***@***.***
|
---- Replied Message ----
| From | Herman Wika ***@***.***> |
| Date | 5/25/2023 15:47 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [hermanwh/master-thesis] Ask questions about the data in your paper (Issue #34) |

Good morning!

The theory and corresponding formulas are primarily used to provide theoretical justification as to why machine learning algorithms may be able to make accurate estimations in the relevant cases. The machine learning models themselves perform calculations and estimations much different than traditional formulas, and thus they are not really relevant in that sense.

I never used UniSim myself with regards to this thesis. I assume the product can still be purchased from Honeywell, the developers. I did, to some extent, use Neqsim, which can be found here: https://equinor.github.io/neqsimhome/
